"""add drop_manager history

Revision ID: 1b748b108b13
Revises: 1ecd410f4553
Create Date: 2024-02-04 00:40:04.678574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b748b108b13'
down_revision: Union[str, None] = '1ecd410f4553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop_managers',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tg_id', sa.String(), nullable=True),
    sa.Column('referral', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drop_managers_id'), 'drop_managers', ['id'], unique=False)
    op.add_column('forms', sa.Column('drop_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forms', 'drop_managers', ['drop_manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'drop_manager_id')
    op.drop_index(op.f('ix_drop_managers_id'), table_name='drop_managers')
    op.drop_table('drop_managers')
    # ### end Alembic commands ###
