"""add drop table

Revision ID: 1ecd410f4553
Revises: 27dd6d58e67d
Create Date: 2024-02-04 00:27:49.514106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecd410f4553'
down_revision: Union[str, None] = '27dd6d58e67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drops',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drops_id'), 'drops', ['id'], unique=False)
    op.add_column('forms', sa.Column('drop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forms', 'drops', ['drop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'drop_id')
    op.drop_index(op.f('ix_drops_id'), table_name='drops')
    op.drop_table('drops')
    # ### end Alembic commands ###
